jobs:
  check-ascii:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check ASCII
      run: 'find . -type f  -name ''*.java'' | xargs file  | grep -qv ASCII || exit
        0  && exit 1

        '
name: Check ASCII
on:
  repository_dispatch:
    types: trigger-ga___checkascii.yml
